### ISSUE TITLE
Squiz.CSS.SemicolonSpacingSniff false positive when style name proceeded by an asterisk

### ISSUE THREAD

**Issue by josephzidell** [squizlabs/PHP_CodeSniffer#2453]
The latest update of PHPCS fails on this code:
```css
.some_class {
	cursor: pointer;
	*cursor: hand;
}
```

With this message: `Style definitions must end with a semicolon`
