### ISSUE TITLE
Wrong detection of Squiz.CSS.DuplicateStyleDefinition with media queries

### ISSUE THREAD

**Issue by adriankirchner** [squizlabs/PHP_CodeSniffer#622]
Here are some more details:
```
$ php phpcs-2.3.2.phar --version
PHP_CodeSniffer version 2.3.2 (stable) by Squiz (http://www.squiz.net)
```
content of `test.css`
```css
@media only screen and (max-width: 480px) {
    header nav.meta a { display: none; }
    header nav.meta a.search { display: block; }
}
```
content of `test-ruleset.xml`
```xml
<?xml version="1.0"?>
<ruleset name="test">
 <description>Test ruleset</description>
 <rule ref="Squiz.CSS.DuplicateStyleDefinition"/>
</ruleset>
```
executing this setup results in the following errors:
```
$ php phpcs-2.3.2.phar --standard=test-ruleset.xml test.css

FILE: ...test.css
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 3 | ERROR | Duplicate style definition found; first defined on line
   |       | 2
----------------------------------------------------------------------

Time: 8ms; Memory: 2.25Mb
```
When I remove the media query the error vanishes.
Please ping me if you need more information.
