### ISSUE TITLE
Allow line breaks in CSS property definitions

### ISSUE THREAD

**Issue by SebastianZ** [squizlabs/PHP_CodeSniffer#799]
Some style guides require to break a line at a specific column. Though line breaks within CSS style definitions are not recognized.

Therefore there should be an option to define at which column a line break must happen and how wrapped lines are indented.

Validating the following CSS with the 'Squiz' ruleset

``` css
#someDIV {
    background: url(/some/very/long/path/to/a/background/image.png)
        repeat scroll 50% 50% #EEE;
}
```

will currently output three errors:

```
 2 | ERROR | [ ] Style definitions must end with a semicolon
 3 | ERROR | [x] Line indented incorrectly; expected 4 spaces, found
   |       |     8
 3 | ERROR | [ ] No style definition found on line; check for missing
   |       |     colon
```

No errors should be output if a line break is required at 80 columns and the indentation for wrapped lines is set to 4 spaces.

Sebastian
